Play travis
Otus-DevOps-2021-02/adv-dev-22_infra pull request #1
Opened 2021-04-25 10:54 UTC by adv-dev-22

2021-04-26 07:58 UTC, mrgreyves requested changes
Здравствуйте! Проверил ваше дз. Оставил комментарий к файлу, так же не забывайте добавлять описание к вашим пр. ДЗ возвращаю на доработку.

2021-04-26 07:58 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Вот тут ошибка

2021-05-02 08:52 UTC, adv-dev-22 commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Добрый день! Честно говоря, немного удивлен несоответствием домашнего задания результату проверки. 
1) В личном кабинете в чате с преподавателем я написал, что этот тест не проходит. Если прием ДЗ осуществляется в ПР комментариях то об этом лучше явно сказать в ДЗ для студентов - пишите все пояснения в ПР-стах, чтобы было взаимопонимание.

2) В дз не указано, что тесты нужно поправить до работающих, или я что-то пропустил? Может быть в ДЗ тогда явно прописывать эти требования?

Тест сейчас поправлю.

2021-05-03 18:21 UTC, mrgreyves approved these changes
Здравствуйте!) В одной из первых лекций курса, в которой рассказывается про git и как устроена сдача дз рассказывается что запускаются тесты которые проверяют базовую часть домашнего задания. И по их результатам вполне можно судить о том выполнено ли домашнее задание или нет. Так же не стоит забывать про описание к вашим пуллреквестам.

2021-05-04 19:47 UTC, merged